### ISSUE TITLE
Noise register values should be reversed

### ISSUE THREAD

**Issue by defensem3ch** [nununoisy/gb-presenter-rs#6]
Lower noise values should happen on the left and higher noise values should happen on the right, reverse of what it is now. This would match the rest of the notes/pitches on the keyboard.

**Comment by nununoisy** [comment]
The current solution for mapping the noise channel to the piano roll is a bit of a hack. I want to fix it for v0.4.0, so this feedback helps a lot.

**Comment by nununoisy** [comment]
Should be fixed in v0.4.0. Let me know if you have any other improvements that could be made.

**Comment by defensem3ch** [comment]
hmm I'm not seeing the difference here. my noise crashes are still happening in the reverse direction
